server:
  port: 20080
spring:
  application:
    name: gateway
  config:
    import:
      - optional:nacos:gateway.properties?refresh=true
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: patientservice # routing configuration
          uri: lb://patientservice # lb for load balance
          predicates:
          - Path=/patient/**
#          filters:
#            - AddRequestHeader=rfp, This is routing filter of add request header for patient service!
        - id: doctorservice
          uri: lb://doctorservice
          predicates:
          - Path=/doctor/**
        - id: bookingservice
          uri: lb://bookingservice
          predicates:
          - Path=/booking/**
        - id: paymentservice
          uri: lb://paymentservice
          predicates:
          - Path=/payment/**
#      default-filters:
#        - AddRequestHeader=rf, This is routing filter of add request header for all service!
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:18999"
              - "http://127.0.0.1:18999"
            allowedMethods: # the allowed ajax request method
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true # whether allow cookie
            maxAge: 360000
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: ph1nix
    password: ph1nix