server:
  port: 20080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:18888
    gateway:
      routes:
        - id: patientservice # routing configuration
          uri: lb://patientservice # lb for load balance
          predicates:
            - Path=/patient/**
#          filters:
#            - AddRequestHeader=rfp, This is routing filter of add request header for patient service!
        - id: doctorservice
          uri: lb://doctorservice
          predicates:
            - Path=/doctor/**
        - id: bookingservice
          uri: lb://bookingservice
          predicates:
            - Path=/booking/**
#      default-filters:
#        - AddRequestHeader=rf, This is routing filter of add request header for all service!