server:
  port: 23004
spring:
  application:
    name: paymentservice
  config:
    import:
      - optional:nacos:payment-service.properties?refresh=true
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_payment?useSSL=false
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      #        namespace: xx
      #        cluster-name: GLA
      config:
        server-addr: localhost:8848
        file-extension: yaml
mybatis:
  type-aliases-package: org.huayuzhang.payment.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    org.huayuzhang: debug
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss:SSS
feign:
  client:
    config:
      default:
        logger-level: FULL
        # logger-level: BASIC
  httpclient:
    enabled: true
    max-connections: 1000
    max-connections-per-route: 250


