server:
  port: 23004
spring:
  datasource:
    url: jdbc:mysql://172.16.238.15:3306/cloud_payment?useSSL=false
#    url: jdbc:mysql://localhost:3306/cloud_payment?useSSL=false
    # driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
mybatis:
  type-aliases-package: org.huayuzhang.payment.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    org.huayuzhang: debug
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss:SSS
feign:
  client:
    config:
      default:
        logger-level: FULL
        # logger-level: BASIC
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50


