server:
  port: 23001
spring:
  application:
    name: patientservice
  config:
    import:
      - optional:nacos:patient-service.properties?refresh=true
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_patient?useSSL=false
    username: root
    password: root
#    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      #        namespace: xx
      #        cluster-name: GLA
      config:
        server-addr: localhost:8848
        file-extension: yaml
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: ph1nix
    password: ph1nix
    listener:
      simple:
        prefetch: 1
mybatis:
  type-aliases-package: org.icare.patient.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    org.icare: debug
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: org.icare.patient.pojo
