@startuml

actor "Front Users" as fu
participant "Frontend Application" as fa
collections "Nacos Clusters" as nacos
participant sc [
    =Service Clusters
    ----
    ""Patient Service""
    ----
    ""Doctor Service""
    ----
    ""Booking Service""
    ----
    ""Payment Service""
    ----
    ""etc.""
]
participant dc [
    =Distributed Cache
    ----
    ""Redis or DragonflyDB""
]

fu -> fa: Using
== Front-end Service==

group Front Proxy
fa -> nginx: frontend request
nginx -> dc: Queue in Cache
dc -> nacos: Search for Service (Cache Penetrate)
nacos -> ndb: Queue service information
ndb --> nacos: IP address, health condition, namespace...
end

nacos -> dc

@enduml
