server:
  port: 23001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_patient?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
#  application:
#    name: patientservice
#  cloud:
#    nacos:
#      server-addr: localhost:23348
#      discovery:
#        cluster-name: GLA
#        namespace: xx
#        ephemeral: false
mybatis:
  type-aliases-package: org.huayuzhang.patient.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    org.huayuzhang: debug
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss:SSS